name: Solicitar Acesso
description: Solicitar Acesso ao Repositório
title: "Gostaria de acesso ao repositório"
labels: [ "senac-devops-na-pratica" ]
assignees: 
  - golino
body:
  - id: senha
    type: input
    attributes:
      label: Senha
      description: 'Senha para acesso ao repositório'
      