name: 'CI Pipeline'

on:
  push:
    branches-ignore:
     - 'main'

jobs:
  compilar_projeto:
    runs-on: ubuntu-latest
    name: 'Compilar Projeto'
    steps:
      - id: checkout
        name: 'Checkout Repositório'
        uses: actions/checkout@v3
        with:
          ref: '${{ github.ref }}'
      - id: configurar_node
        name: 'Configurar Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: instalar_pacotes
        name: 'Instalar Pacotes'
        shell: bash
        run: |
          cd src
          npm install