name: Solicitação de Acesso

on:
  issues:
   types: [ opened, edited ]

jobs:
  check_issue:
    runs-on: ubuntu-latest
    name: 'Verificar informações da Issue'
    steps:
      - id: dados_issue
        name: 'Dados da Issue'
        uses: actions/github-script@v6
        with:
          script: |
            const eventPayload = context.payload;
            const issueNumber = eventPayload.issue.number;
            const user = '${{ github.actor }}';
            const body = String(eventPayload.issue.body);
            const senha = body.replace('### Senha\n\n', '');

            core.setCommandEcho(true);
            core.setOutput('USUARIO', user);
            core.setOutput('ISSUE', issueNumber);
            core.setCommandEcho(false);
            
            core.setOutput('SENHA', senha);
      - id: verificar_senha
        name: 'Verificar Senha'
        uses: actions/github-script@v6
        with:
          script: |
            if ('${{ steps.dados_issue.outputs.senha }}' == '${{ secrets.SENHA_SENAC }}' ) {
              console.log('Acesso OK');
              core.setOutput('ACESSO_OK', 'sim');
            } else { 
              console.log('Senha Incorreta');
              core.setOutput('ACESSO_OK', 'não');
            }
      - id: incluir_usuario_time
        if: steps.verificar_senha.outputs.ACESSO_OK == 'sim'
        name: 'Incluir Usuário no Time'
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Seguindo');

            